Split type-deduction lattice/constraints analysis from type analysis.
souffle-lang/souffle pull request #1734
Opened 2020-11-12 03:12 UTC by azreika

Reduces the bloat in both significantly, will be much easier to maintain and work with. Resolves issue #1733. 

Should be merged AFTER PR #1725 (as it's a branch off of it).

2020-11-16 05:20 UTC, mmcgr requested changes
Most of the comments are actually about moved code, rather than new code, so you may not want to address those here.

2020-11-16 05:20 UTC, mmcgr commented on src/ast/analysis/TypeConstraints.cpp
> +        unsigned index;
This is a little bizarre - index is std::size_t, int, and unsigned. Standardise on ... size_t.

2020-11-16 05:20 UTC, mmcgr commented on src/ast/analysis/TypeConstraints.cpp
> +        // See #1296 and tests/semantic/type_system4
This can probably be removed.
```suggestion
```

2020-11-17 01:13 UTC, azreika commented
I'll address these code-style changes in the next type-analysis PR (they are all in code that has been moved).

2020-11-17 03:13 UTC, mmcgr approved these changes

2020-11-17 05:56 UTC, merged

2020-11-23 06:35 UTC, azreika commented
In the clean-up PR, printing should be cleaned up for the type-related analyses too (i.e. the main type analysis + polymorphic + functor analyses).