Add functional dependency constraints
souffle-lang/souffle pull request #1786
Opened 2020-12-06 04:15 UTC by XiaowenHu96

**This PR is still under progress -- see todo list.**

This PR introduces functional dependency constraint (aka choice constraint, aka keys).

The user specifies the constraints at relation declaration, by using the keyword `keys` followed by a list of relation attributes, separated by a comma.
```Datalog
.decl student(Name:symbol, Majr:symbol, Yr:number) keys Name
```
The above example makes sure the `Name` in relation uniquely defines a student.

The user can also write down several keys
```Datalog
.decl student(Name:symbol, Majr:symbol, Yr:number) keys Name, Majr
```
The above example makes sure `Name` uniquely defines a student and `Majr` also uniquely defines a student.

You can also have multiple attributes that serve as a single key.
```Datalog
.decl student(Name:symbol, Majr:symbol, Yr:number) keys (Name, Majr)
```
The pair `(Name, Major)` uniquely defines a student.

to fix:
- [ ]  Fact literal is not projected with guarded conditions (failing semantic/keys1).
- [ ]  Stop RemoveRelationCopiesTransformer from removing relation with different constraints (failing semantic/keys2).

2020-12-06 22:47 UTC, b-scholz commented on src/ast/FunctionalConstraint.h
> + * For relation (x, y), we have x -> y, a function from x to y, i.e. x uniquely identifies some y value
This remark since to be outdated; please update to latest syntax.

2020-12-06 22:47 UTC, b-scholz commented on src/ast/FunctionalConstraint.h
> +    void print(std::ostream& os) const override {
Can you ensure that the printed AST is identical to the parsed AST, e.g., `keys a,b,(c,d)`?

2020-12-06 22:47 UTC, b-scholz commented on src/ast/FunctionalConstraint.h
> +        os << "Keys: ";
Just remove this line?

2020-12-06 22:47 UTC, b-scholz commented on src/ast/transform/SemanticChecker.cpp
> +                report.addError("Key not found in relation definition.", fd->getSrcLoc());
Please add the name of the key in the error message.

2020-12-07 03:00 UTC, azreika requested changes
Changes look great! Just minor comments.

2020-12-07 03:07 UTC, azreika commented on src/ast2ram/ClauseTranslator.cpp
> +    VecOwn<ram::Condition> dependencies;
Could you move this part out into its own method? e.g. `getFunctionalDependencies(...)`

2020-12-07 04:20 UTC, XiaowenHu96 commented
@joshuakarp  Can you double-check the 3-colour problem? With the new input, the result is not colourable. Is this the expected behaviour?

2020-12-07 04:48 UTC, joshuakarp commented
> @joshuakarp Can you double-check the 3-colour problem? With the new input, the result is not colourable. Is this the expected behaviour?

Yes, that's expected. The choice constraint is used only to ensure that a node has no more than 1 allocated colour, but there's only a very naive check to ensure that this allocated colour will be a valid colour (i.e. if it finds any adjacent node, n, it won't colour the node with n's colour, but this only works for the first adjacent node found). When I've got a bit more time after exams, I can take a look at this to figure out how we can actually allocate a valid colour with choice.

2020-12-07 08:13 UTC, azreika approved these changes

2020-12-07 08:28 UTC, azreika commented
Jenkins test this please

2020-12-08 01:32 UTC, merged